# Generated by Django 4.2.3 on 2023-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ipaddress',
            new_name='IP_address',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='sshport',
            new_name='SSH_port',
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, choices=[('mikrotik', 'Mikrotik'), ('cisco', 'Cisco')], max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
