# Generated by Django 4.2.3 on 2023-07-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkManager', '0002_rename_ipaddress_device_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('router', 'Router'), ('switch', 'Switch')], max_length=255),
        ),
    ]
